sudo: required

language: node_js

cache:
    directories:
      - node_modules

node_js:
  - "12"

script:
  - echo "npm test temporarily disabled"

install:
  - yarn
  - bash .travis/build.sh || true
  - ls build || true
  - ls build-ropsten || true

deploy:
  - provider: gcs
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_SECRET_KEY_ID
    bucket: dev-dmm.knstats.com
    skip_cleanup: true
    local-dir: build-ropsten
    cache_control: "no-cache"
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^develop$

  - provider: gcs
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_SECRET_KEY_ID
    bucket: dev-dmm-split-trade.knstats.com
    skip_cleanup: true
    local-dir: build
    cache_control: "no-cache"
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^develop$

  - provider: gcs
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_SECRET_KEY_ID
    bucket: staging-dmm.knstats.com
    skip_cleanup: true
    local-dir: build
    cache_control: "no-cache"
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^staging$

  - provider: gcs
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_SECRET_KEY_ID
    bucket: testnet.dmm.exchange
    skip_cleanup: true
    local-dir: build
    cache_control: "public, max-age=900"
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^develop$

  - provider: gcs
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_SECRET_KEY_ID
    bucket: testnet.dmm.exchange
    skip_cleanup: true
    local-dir: build
    cache_control: "public, max-age=60"
    glob: index.html
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^develop$

  - provider: gcs
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_SECRET_KEY_ID
    bucket: dmm.exchange
    skip_cleanup: true
    local-dir: build
    cache_control: "public, max-age=900"
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^main$

  - provider: gcs
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_SECRET_KEY_ID
    bucket: dmm.exchange
    skip_cleanup: true
    local-dir: build
    cache_control: "public, max-age=60"
    glob: index.html
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^main$
